package org.spoon.tracability.spoon.processors;

import org.slf4j.Logger;
import spoon.processing.AbstractProcessor;
import spoon.reflect.code.*;
import spoon.reflect.declaration.CtClass;
import spoon.reflect.declaration.CtField;
import spoon.reflect.declaration.CtMethod;
import spoon.reflect.declaration.ModifierKind;
import spoon.reflect.reference.CtTypeReference;
import java.util.Set;

/**
 * The type Class processor.
 */
public class ClassProcessor extends AbstractProcessor<CtClass> {
    private static final Logger logger = org.slf4j.LoggerFactory.getLogger(ClassProcessor.class);
    @Override
    public void process(CtClass ctClass) {
        // creation d'une reference vers la classe org.slf4j.Logger
        final CtTypeReference<org.slf4j.Logger> loggerRef = getFactory().Code().createCtTypeReference(org.slf4j.Logger.class);
       // creation d'une reference vers la classe org.slf4j.LoggerFactory
        final CtTypeReference<org.slf4j.LoggerFactory> loggerFactoryRef = getFactory().Code().createCtTypeReference(org.slf4j.LoggerFactory.class);
        // creation d'un attribut static de type org.slf4j.Logger
        final CtField<org.slf4j.Logger> loggerField = getFactory().Core().createField();
        loggerField.<CtField<org.slf4j.Logger>>setSimpleName("logger");
        loggerField.<CtField<org.slf4j.Logger>>setType(loggerRef);
        loggerField.<CtField<org.slf4j.Logger>>addModifier(ModifierKind.PRIVATE);
        loggerField.<CtField<org.slf4j.Logger>>addModifier(ModifierKind.STATIC);
        loggerField.<CtField<org.slf4j.Logger>>addModifier(ModifierKind.FINAL);
        // ajouter la generation automatique du commentaire
        final CtComment autoGeneratedComment = getFactory().createComment();
        autoGeneratedComment.setContent("Automatically generated by Spoon");
        loggerField.addComment(autoGeneratedComment);
        // creation d'un bloc d'initialisation static de statement
        final String expression = loggerFactoryRef + ".getLogger(" + ctClass.getSimpleName() + ".class.getName())";
        final CtCodeSnippetExpression<org.slf4j.Logger> loggerExpression = getFactory().Code().createCodeSnippetExpression(expression);
        loggerField.setDefaultExpression(loggerExpression);

        String className = ctClass.getSimpleName();
        switch (className) {
            case "ProductServiceImpl":
                ctClass.addFieldAtTop(loggerField);
                addLogToMethod(ctClass.getMethods());
                if (!ctClass.getMethodsByName("getProductById").isEmpty()) {
                    CtMethod method = (CtMethod) ctClass.getMethodsByName("getProductById").get(0);
                    method.getBody().addStatement(
                            method.getBody().getStatements().size() - 1, getFactory()
                                    .Code()
                                    .createCodeSnippetStatement("logger.info(\"product called {} price {}\",  productEntity.getName(), productEntity.getPrice());"));


                }
                break;
            case "UserServiceImpl":
                ctClass.addFieldAtTop(loggerField);
                // creation d'une reference vers la classe org.slf4j.MDC
                final CtTypeReference<org.slf4j.MDC> mdcReference = getFactory().Code().createCtTypeReference(org.slf4j.MDC.class);
                // creation de l'expression "MDC.put("user", userEntity.getEmail())"
                final String mdcExpression = mdcReference + ".put(" + "\"user\"" + ", userToFound.getEmail()" + ")";
                final CtCodeSnippetExpression<org.slf4j.Logger> mdcExpressionSnippet = getFactory().Code().createCodeSnippetExpression(mdcExpression);
                // transformation de l'expression en statement
                final CtStatement mdcStatement = getFactory().Code().createCodeSnippetStatement(mdcExpressionSnippet.toString());
                // ajouter les messages de tracage dans les methodes
                addLogToMethod(ctClass.getMethods());
                // on va chercher la methode "authenticateUser" et on ajoute le statement
                if (!ctClass.getMethodsByName("authenticateUser").isEmpty()) {
                    CtMethod method = (CtMethod) ctClass.getMethodsByName("authenticateUser").get(0);
                    CtBlock methodBody = method.getBody();
                    for (int i = 0; i < methodBody.getStatements().size(); i++) {
                        CtStatement statement = methodBody.getStatements().get(i);
                        // on cherche si l'utilisateur est connecter pour ajouté le statement
                        if (statement.toString().contains("if (userToFound.getPassword().equals(password)) {")) {
                            CtIf ifStatement = (CtIf) statement;
                            CtBlock thenBlock = ifStatement.getThenStatement();
                            // on ajoute le statement juste avant le return
                            thenBlock.insertBegin(mdcStatement);
                            thenBlock.insertBegin(getFactory().Code().createCodeSnippetStatement("logger.info(\"User authenticated\");"));
                        }
                    }
                }
                break;
            default:
                break;
        }
    }


    /**
     * Add log to method.
     *
     * @param methods the methods to add log
     */
    private void addLogToMethod(Set<CtMethod> methods) {
        methods.forEach(method -> {
            // on extrait le nom de la methode
            String methodName = method.getSimpleName();
            // on ajoute le message dans tous les methode sauf dans la méthode de l'authentification
            if (!methodName.equals("authenticateUser")) {
                // on creer le statement de l'appele de méthode
                String logStatement = "logger.info(\"" + methodName + " method called\")";
                CtStatement logStatementObject = getFactory().Code().createCodeSnippetStatement(logStatement);
                // on ajoute le statement au debut de la methode
                method.getBody().insertBegin(logStatementObject);
            }
        });
    }
}
